name: php
icon: php
title: PHP

services:
- name: php
  title: PHP
  service: php
  required: true
  volumes:
  - name: files
    size: 50
  links:
  - name: db
    service: mariadb

- name: nginx
  title: Nginx
  service: php-nginx
  required: true
  containers:
  - name: nginx
    env:
    - name: NGINX_VHOST_PRESET
      value: php
  links:
  - name: backend
    service: php

- name: mariadb
  title: MariaDB
  service: mariadb
  required: true  
  volumes:
  - name: data
    size: 20

- name: httpd
  title: Apache HTTP server
  service: php-httpd
  disabled: true
  containers:
  - name: httpd
    env:
    - name: APACHE_VHOST_PRESET
      value: php
  links:
  - name: backend
    service: php

- name: postgres
  title: PostgreSQL
  service: postgres
  disabled: true  
  volumes:
  - name: data
    size: 20
    
